### ISSUE TITLE
Unable to send a mail

### ISSUE THREAD

**Issue by fjoalland** [lmangani/sentinl#132]
Hi,

Thank you for your application ! I would like to use your application to send a mail when we have some errors. But I have a problem when the watcher is executed :

`[13:35:46.055] [info][status][Sentinl][email] Error: timedout while connecting to smtp server
 at module.exports (D:\ELK\kibana-5.3.2-windows-x86\plugins\sentinl\node_modules\emailjs\smtp\error.js:3:13)
 at TLSSocket.timedout (D:\ELK\kibana-5.3.2-windows-x86\plugins\sentinl\node_modules\emailjs\smtp\response.js:32:29)
 at TLSSocket.g (events.js:291:16)
 at emitNone (events.js:86:13)
 at TLSSocket.emit (events.js:185:7)
 at TLSSocket.Socket._onTimeout (net.js:342:8)
 at ontimeout (timers.js:380:14)
 at tryOnTimeout (timers.js:244:5)
 at Timer.listOnTimeout (timers.js:214:5)`

I already researched in your issues and the issues of the node module **emailjs**, but I found nothing.

The configuration of my mail is :
```
sentinl:
  settings:
    email:
      active: true
      user: gmail@gmail.com
      password: mdpmdp
      host: smtp.gmail.com
      ssl: true
    report:
      active: true
      tmp_path: /tmp/
```

Thank you,

FJ
