### ISSUE TITLE
Feature request: Support regional timezone from Kibana configuration 

### ISSUE THREAD

**Issue by yabir** [lmangani/sentinl#381]
Until now Sentinl has two options for timezones to run the watchers: `utc (default)` and `local`.

It would be nice to have another option that comes directly from the kibana's configuration `(Kibana > Management > Advanced Settings > dateFormat:tz)` since it has already the timezone we're using and it will not be necessary to change it in the Kibana host (in order to use the `local` option).

This could be configured in the Sentinl config, perhaps like this:

```yaml
 sentinl:
   es:
     watcher:
        schedule_timezone: 'kibana'
```
