### ISSUE TITLE
Unable to Send Report

### ISSUE THREAD

**Issue by ankit22550** [lmangani/sentinl#459]
1. Sentinl and Kibana version :- 6.2.3

2. Issue description:-  unable to send report

3. Reproducing the issue step-by-step:- 
```
  log   [10:56:47.629] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to yellow - Search Guard copy JWT params disabled
  log   [10:56:47.630] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to yellow - Search Guard multitenancy disabled
  log   [10:56:47.692] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to yellow - Routes for Search Guard configuration GUI registered. This is an Enterprise feature.
  log   [10:56:47.701] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to yellow - Search Guard system routes registered.
  log   [10:56:47.702] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to green - Search Guard plugin initialised.
  log   [10:56:47.711] [info][status][plugin:sentinl@6.0.0] Status changed from uninitialized to green - Ready
  log   [10:56:47.732] [info][status][plugin:console@6.2.3] Status changed from uninitialized to green - Ready
  log   [10:56:47.740] [info][status][plugin:metrics@6.2.3] Status changed from uninitialized to green - Ready
  log   [10:56:47.774] [info][listening] Server running at https://10.192.226.4:5601
  log   [10:56:47.824] [info][status][plugin:elasticsearch@6.2.3] Status changed from yellow to green - Ready
  log   [10:56:47.827] [info][Sentinl][init] initializing ...
  log   [10:56:47.891] [info][Sentinl][init_indices] checking watcher_alarms index ...
  log   [10:56:55.752] [info][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] executing
  log   [10:56:55.770] [warning][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] "elasticsearch.plugins" not available when running from kibana
  log   [10:56:56.003] [info][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] successfully applied condition
  log   [10:56:56.004] [info][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] no transform found
  log   [10:56:56.019] [info][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] successfuly executed
  log   [10:57:02.409] [error][Sentinl][action] report action: fail to execute report: fail to authenticate via Search Guard, user: admin: No node found for selector: #username
^C^C
```

4. Expected results vs. actual results

5. Sample of data

6. Additional details
```
  log   [10:56:47.629] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to yellow - Search Guard copy JWT params disabled
  log   [10:56:47.630] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to yellow - Search Guard multitenancy disabled
  log   [10:56:47.692] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to yellow - Routes for Search Guard configuration GUI registered. This is an Enterprise feature.
  log   [10:56:47.701] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to yellow - Search Guard system routes registered.
  log   [10:56:47.702] [info][status][plugin:searchguard@6.2.3] Status changed from yellow to green - Search Guard plugin initialised.
  log   [10:56:47.711] [info][status][plugin:sentinl@6.0.0] Status changed from uninitialized to green - Ready
  log   [10:56:47.732] [info][status][plugin:console@6.2.3] Status changed from uninitialized to green - Ready
  log   [10:56:47.740] [info][status][plugin:metrics@6.2.3] Status changed from uninitialized to green - Ready
  log   [10:56:47.774] [info][listening] Server running at https://10.192.226.4:5601
  log   [10:56:47.824] [info][status][plugin:elasticsearch@6.2.3] Status changed from yellow to green - Ready
  log   [10:56:47.827] [info][Sentinl][init] initializing ...
  log   [10:56:47.891] [info][Sentinl][init_indices] checking watcher_alarms index ...
  log   [10:56:55.752] [info][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] executing
  log   [10:56:55.770] [warning][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] "elasticsearch.plugins" not available when running from kibana
  log   [10:56:56.003] [info][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] successfully applied condition
  log   [10:56:56.004] [info][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] no transform found
  log   [10:56:56.019] [info][Sentinl][watcher e44fd4a0-6fde-11e8-b569-9f1f23806daa] successfuly executed
  log   [10:57:02.409] [error][Sentinl][action] report action: fail to execute report: fail to authenticate via Search Guard, user: admin: No node found for selector: #username
^C^C
```

below is my kibana configuration file:-
```
sentinl:
   es:
    host: node-1
    port: 9200
    protocol: 'https'
    results: 50
    timefield: '@timestamp'
    default_index: watcher
    default_type: sentinl-watcher
    alarm_index: watcher_alarms
    alarm_type: sentinl-alarm
    script_type: sentinl-script
   settings:
    email:
      active: true
      user: ankit2.kumar@orange.com
      host: meplus-smtp.si.francetelecom.fr
      ssl: false
      timeout: 10000  # mail server connection timeout
    authentication:
      enabled: true
      username: 'admin'
      password: 'admin'
      cert:
        selfsigned: true
    report:
      active: true
      executable_path: '/usr/bin/google-chrome' # path to Chrome v59+ or Chromium v59+
      timeout: 5000
      authentication:
        enabled: true
        mode:
          searchguard: true
```
