### ISSUE TITLE
only get "slack message delivery disabled" even after enabling web-hook in yaml file

### ISSUE THREAD

**Issue by michael-s-downs** [lmangani/sentinl#485]
1. Sentinl and Kibana version - version 6.2.2

2. I want to send alerts to my slack channel:  

I configured a slack channel called "#yellow_alerts_test" with an incoming-webhook app.  I tested the web-hook by POSTing to it from a tool, and the webhook works fine.  

I then added the generated webhook address and username to Kibana.yml as shown below.   

---
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://10.1.2.17:9200

sentinl:
  settings:
#    authentication:
#      enabled: true
#    email:
#      active: true
#      host: 'localhost'
#      ssl: false
#    report:
#      active: false
    slack:
      active: true
      username: 'incoming-webhook-sentinel'
      hook: 'https://hooks.slack.com/services/T029YN2CF/BBD4VUN6L/7Ak9lnykRsd7E4R1pYQ[truncated]...'
      channel: '#yellow_alerts_test'

In sentinl UI, I created a test alert with no conditions, scheduled every 5 minutes, and gave it the action to alert every 5 minutes.  This is the raw alert definition:

{
  "actions": {
    "New slack action h0yeqh2ovej": {
      "throttle_period": "0h0m1s",
      "slack": {
        "channel": "#yellow_alerts_test",
        "message": "There is no content to share at this time except success in the alerting pipeline",
        "stateless": false
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "e2e-prod-*"
        ],
        "body": {}
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 0"
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 5 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "Alert_Always"
}

I built and ran the app in docker.

I either run the alert and/or let it run itself, and I see the alert logged in the Sentinl section of the Kibana UI, but no messages show up in Slack.  

In the app logs I see:

{"type":"log","@timestamp":"2018-07-02T21:20:00Z","tags":["warning","Sentinl","action"],"pid":1,"message":"slack message delivery disabled"} 

What step did I miss or where is it wrong?  Thanks in advance for your help!

MIke D.

**Comment by lmangani** [comment]
Hi @michael-s-downs it seems kibana is not parsing the configuration as expected and going with defaults. My first guess would be a malformed configuration structure.

````

if (!slack || !config.settings.slack.active) {
  log.warning('slack message delivery disabled');

```

**Comment by havlan** [comment]
@michael-s-downs post more logs! use https://help.github.com/articles/creating-and-highlighting-code-blocks/ to make it easier to help you. Are you using docker-compose?

**Comment by victorbuttner** [comment]
HI! I'm having the same problem here, please checkout my kibana.yml and log from docker-compose

```
#i18n.locale: "en"
sentinl:
  es:
    host: 'elasticsearch'
    port: 9200
    protocol: 'http'
    # results: 50
    # timefield: '@timestamp'
    # default_type: 'doc'
    alarm_index: 'watcher_alarms'
    alarm_type: 'sentinl-alarm'
  settings:
    email:
      active: true
      host: 'localhost'
      # user: 'admin'
      # password: 'password'
      # port: 25
      # domain: 'beast.com'
      # ssl: false
      # tls: false
      # authentication: ['PLAIN', 'LOGIN', 'CRAM-MD5', 'XOAUTH2']
      # timeout: 10000  # mail server connection timeout
      # cert:
      #   key: '/full/sys/path/to/key/file'
      #   cert: '/full/sys/path/to/cert/file'
      #   ca: '/full/sys/path/to/ca/file'
    slack:
      active: true
      #token: 
      #username: 'kibana'
      hook: 'https://hooks.slack.com/services/T1NM5S7P1/BD9JWV35L/7alFXgcQ1.....'
      #channel: '#alerts'
``` 

```
{"type":"log","@timestamp":"2018-11-08T20:08:00Z","tags":["info","Sentinl","watcher_handler"],"pid":1,"message":"successfully applied condition"}
kibana_1                   | {"type":"log","@timestamp":"2018-11-08T20:08:00Z","tags":["info","Sentinl","watcher_handler"],"pid":1,"message":"successfuly executed"}
kibana_1                   | {"type":"log","@timestamp":"2018-11-08T20:08:00Z","tags":["error","Sentinl"],"pid":1,"message":"CPU User AVG: slack action : slack message delivery disabled: Error: slack message delivery disabled\n    at /usr/share/kibana/plugins/sentinl/server/lib/actions/do_actions.js:441:19\n    at <anonymous>"}```

Please anyone know that can be happen? Using version 6.4.0 from relase tag ` tag-6.4.2-0`
