### ISSUE TITLE
how to change UTC time to   Local time?

### ISSUE THREAD

**Issue by aabababb** [lmangani/sentinl#544]
1. Sentinl and Kibana version 6.2.4

2. how to change UTC time to   Local time?

4. Expected results vs. actual results
how to change UTC time to   Local time?
UTC time is 06:16:47

Local time is 14:16:47
```
  "transform": {
    "script": {
      "script": "new Date('{{#payload.hits.hits}}{{_source.@timestamp}}{{/payload.hits.hits}}' ).values+8"
    }
  }
```

this transform not  work?

**Comment by sergibondarenko** [comment]
Put this in kibana.yml
```
sentinl:
  es:
    watcher:
       schedule_timezone: local
```
