### ISSUE TITLE
Is it possible to hide undesired actions from the "Add action" menu ?

### ISSUE THREAD

**Issue by lbesuchet** [lmangani/sentinl#605]
Everything is in the title..
I tried to confgure something like this, but this has no effect:
```
sentinl:
  settings:
    slack:
      active: false
    webhook:
      active: false
```
