### ISSUE TITLE
Authentication problem with Sentinl 6.4.0 and SearchGuard

### ISSUE THREAD

**Issue by ghost** [lmangani/sentinl#671]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |  6.4.0       |
| Elasticsearch | 6.4.0        |
| Server OS    |  RHEK 6.9       |
| Browser      |   Firefox 64.0.2      |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [X] Source
- Other: 

#### Bug Description

After the installation, I started kibana (with this config in kibana.yml):
```
sentinl:
  es:
    protocol: "https"
    host: "XXX.XX.XXX.XXX"
    port: 9200
    timefield: '@timestamp'
    default_index: watcher
    default_type: sentinl-watcher
    alarm_index: watcher_alarms
    alarm_type: sentinl-alarm
    script_type: sentinl-script
    results: 50
  settings:
    authentication:
      enabled: true
      username: "kibanaserver"
      password: "kibanaserver"
      impersonate: true
      #cert:
      #   selfsigned: true
```
Then, when I open the sentinl module in kibana, there's an alert showing this:

> Watchers: list watchers : list watcher : Authentication Exception

#### Steps to Reproduce
1. Install Sentinl
2. Follow this guide: https://sentinl.readthedocs.io/en/docs/HOWTO-Sentinl-and-SearchGuard/
3. Give the permisions through searchguard web
4. As an admin or sentinl user, open the sentinl module
5. Alert launched
6. Then, followed this link: https://github.com/sirensolutions/sentinl/issues/600
7. As an admin or sentinl user, open the sentinl module
8. Alert launched

#### Expected Behavior

No problems with authentication

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Screenshots (if relevant)

![image](https://user-images.githubusercontent.com/2014251/51839206-5a57bd00-22e7-11e9-8d4e-92586afab245.png)
![image](https://user-images.githubusercontent.com/2014251/51839217-680d4280-22e7-11e9-8a74-47b6989543dc.png)

![image](https://user-images.githubusercontent.com/2014251/51839282-968b1d80-22e7-11e9-895e-396c1eff659e.png)
![image](https://user-images.githubusercontent.com/2014251/51839308-a6a2fd00-22e7-11e9-95ed-65a94cc959fe.png)

![image](https://user-images.githubusercontent.com/2014251/51839230-74919b00-22e7-11e9-998a-65486a912121.png)

#### Errors in Browser Console (if relevant)
```
```

#### Kibana logs and/or server output (attached if relevant)

```
  log   [13:14:33.306] [info][status][plugin:searchguard@6.4.0-17] Status changed from yellow to green - Search Guard plugin initialised.
  log   [13:14:33.311] [info][status][plugin:sentinl@6.4.2] Status changed from uninitialized to green - Ready
  log   [13:14:33.318] [info][status][plugin:console@6.4.0] Status changed from uninitialized to green - Ready
  log   [13:14:33.322] [info][status][plugin:metrics@6.4.0] Status changed from uninitialized to green - Ready
  log   [13:14:33.359] [info][listening][server][http] Server running at http://XXX.XX.XX.XXX:5601
  log   [13:14:33.493] [info][status][plugin:elasticsearch@6.4.0] Status changed from yellow to green - Ready
  log   [13:14:33.541] [info][Sentinl][init] initializing ...
  log   [13:14:33.608] [info][Sentinl][init] Chrome bin found at: /usr/share/kibana/plugins/sentinl/node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome
  log   [13:14:33.703] [info][Sentinl][init_indices] checking watcher index ...
  log   [13:14:33.718] [info][Sentinl][init] PhantomJS bin found at: /usr/share/kibana/plugins/sentinl/phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  log   [13:14:33.760] [info][Sentinl][init_indices] checking watcher_alarms-2019.01.28 index ...
  log   [13:14:33.803] [info][Sentinl][init_indices] creating watcher_alarms-2019.01.28 index ...
```

#### Any additional information
```
curl -XGET -u admin:admin -k "https://XXX.XX.XX.XXX:9200"
{
  "name" : "Z_hnBqB",
  "cluster_name" : "searchguard_demo",
  "cluster_uuid" : "-wfdBRq5RWu_9ZJA-uGmPA",
  "version" : {
    "number" : "6.4.0",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "595516e",
    "build_date" : "2018-08-17T23:18:47.308994Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
The same happens with the user sentinl
Both of them shows all the indices when I run:
```
curl -XGET -u sentinl:sentinl -k "https://XXX.XX.XX.XXX:9200/_cat/indices"

curl -XGET -u admin:admin "http://XXX.XX.XX.XXX:5601/api/sentinl/list/watchers"
{"statusCode":401,"error":"Unauthorized","message":"Authentication Exception"}[

curl -XGET -u sentinl:sentinl "http://XXX.XX.XX.XXX:5601/api/sentinl/list/watchers"
{"statusCode":401,"error":"Unauthorized","message":"Authentication Exception"}#

```

**Comment by sergibondarenko** [comment]
Did you configure the sg_roles.yml like it is specified in my comment? https://github.com/sirensolutions/sentinl/issues/600#issuecomment-435936760 Seems SearchGuards prohibits read access to the `watcher` index. Look at the Elasticsearch log for details. You should see SearchGuard messages there which explain what exact operations are blocked.

Why do you save watcher in the `watcher` index? If you are ok saving watchers to the default index `.kibana`, put this config
```
sentinl:
  es:
    protocol: "https"
    host: "XXX.XX.XXX.XXX"
    port: 9200
    timefield: '@timestamp'
    results: 50
  settings:
    authentication:
      enabled: true
      username: "kibanaserver"
      password: "kibanaserver"
      impersonate: true
```

Notice, you need the `impersonate: true` option only if you want to specify login and password per watcher. Make it `impersonate: false` if you are ok when all watchers are authenticated by `kibanaserver` user.

**Comment by sergibondarenko** [comment]
I recommend you to put the following defaults and then check the log
```
sentinl:
  es:
    protocol: "https"
    host: "XXX.XX.XXX.XXX"
    port: 9200
    timefield: '@timestamp'
    results: 50
  settings:
    authentication:
      enabled: true
      username: "kibanaserver"
      password: "kibanaserver"
      impersonate: true
```
