### ISSUE TITLE
about webhook in kibana.yml config

### ISSUE THREAD

**Issue by BigShake** [lmangani/sentinl#755]
In the kibana.yml:
```
sentinl:
  settings:
    webhook:
      active: false
      host: 'localhost'
      port: 9200
      # use_https: false
      # path: ':/{{payload.watcher_id}}'
      # body: '{{payload.watcher_id}}{payload.hits.total}}'
      # method: POST
```
but in your code(/sentinl-master/server/lib/actions/do_actions.js):
```
options = {
  hostname: action.webhook.host ? action.webhook.host : 'localhost',
  port: action.webhook.port ? action.webhook.port : 80,
  method: action.webhook.method ? action.webhook.method : 'GET',
  headers: action.webhook.headers ? action.webhook.headers : {},
  auth: action.webhook.auth ? action.webhook.auth : undefined,
  path: mustache.render(action.webhook.path, templateData)
};
```
and 
```
const dataToWrite = (options.method !== 'GET' && action.webhook.body) ?
  mustache.render(action.webhook.body, templateData) : undefined;
if (dataToWrite) {
  options.headers['Content-Length'] = Buffer.byteLength(dataToWrite);
}

req = http.request(options, function (res) { // to-do: refactor to use http client which returns promise, e.g. axios
  res.setEncoding('utf8');
  res.on('data', function (chunk) {
    log.debug(`webhook response: ${chunk}`);
  });
});

req.on('error', function (err) {
  log.error(`fail to ship webhook, ${err}`);
});
if (dataToWrite) {
  req.write(dataToWrite);
}
req.end();
```

if i config in my kibana.yml,but the code does not use my webhook config, i want to use this webhook config , i need a default webhook config in the kibana.yml
